version: "3.7"
services:
  nginx:
    image: dherv/watchers-server-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    # restart: unless_stopped
  app:
    image: dherv/watchers-server-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: production
    # volumes:
    #   - /var/www/storage:cached
    # expose:
    #   - "9000"
    # restart: always
    # env_file: ".env.prod"
